# Generated by Django 2.0.5 on 2019-04-08 14:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50)),
                ('is_active', models.CharField(default='1', max_length=20)),
                ('vendor_id', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('approval_status', models.CharField(default='1', max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('due_amount', models.FloatField(default=0.0)),
                ('json_data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_item_id', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billdotcom.Bill')),
            ],
        ),
    ]
