# Generated by Django 2.0.5 on 2019-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billdotcom', '0002_billitem_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
