# Generated by Django 2.0.5 on 2019-04-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billdotcom', '0004_auto_20190417_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsession',
            name='challenge_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
